// apps/backoffice/src/app/page.tsx
import { Button } from '@/components/ui/button';
import {
  Card,
  CardDescription,
  CardHeader,
  CardTitle,
} from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';

export default function Index() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-center gap-6 bg-background p-8">
      <div className="flex items-center gap-3">
        <h1 className="text-3xl font-bold tracking-tight">
          Kryptr Backoffice
        </h1>
        <Badge variant="secondary">scaffold</Badge>
      </div>
      <Card className="w-full max-w-md">
        <CardHeader>
          <CardTitle>shadcn/ui ready</CardTitle>
          <CardDescription>
            Base component set installed: button, card, input, label, badge,
            table, select, dialog, separator, skeleton, tabs, dropdown-menu,
            sonner, avatar, tooltip, sheet. The deck agent builds the real
            dashboard on feat/backoffice-dashboard.
          </CardDescription>
        </CardHeader>
      </Card>
      <Button variant="outline" disabled>
        Dashboard coming in Wave 1
      </Button>
    </main>
  );
}

// apps/frontoffice/src/app/App.vue
<script setup lang="ts">
import { Button } from '@kryptr/shared-ui/vue/button';
import { Badge } from '@kryptr/shared-ui/vue/badge';
import { Input } from '@kryptr/shared-ui/vue/input';
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from '@kryptr/shared-ui/vue/card';
</script>

<template>
  <main class="bg-background flex min-h-screen items-center justify-center p-8">
    <Card class="w-full max-w-md">
      <CardHeader>
        <CardTitle>Kryptr Frontoffice</CardTitle>
        <CardDescription>
          shadcn-vue smoke page — components live in
          <code>@kryptr/shared-ui</code>
        </CardDescription>
      </CardHeader>
      <CardContent class="grid gap-4">
        <Badge class="w-fit">Wave 0</Badge>
        <Input placeholder="Search assets…" aria-label="Search assets" />
        <Button>Connect Wallet</Button>
      </CardContent>
    </Card>
  </main>
</template>
